# SPDX-FileCopyrightText: Copyright (c) 2011-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
errors:
  - yegor256@gmail.com
  - krzysztof.krason@gmail.com
# alerts:
#   github:
#     - yegor256

tags:
  - pdd
  - bug
