architect:
- krzyk
- yegor256
- davvd
install:
- sudo gem install --no-ri --no-rdoc pdd
- sudo gem install --no-ri --no-rdoc est
assets:
  secring.gpg: yegor256/home#assets/secring.gpg
  settings.xml: yegor256/home#assets/qulice/settings.xml
  pubring.gpg: yegor256/home#assets/pubring.gpg
  s3cfg: yegor256/home#assets/s3cfg
merge:
  script: |-
    pdd --source=$(pwd) --verbose --file=/dev/null --exclude=qulice-maven-plugin/src/it/**/*.java,qulice-checkstyle/src/test/resources/com/qulice/checkstyle/AtClauseOrder.java
    est --dir=est --file=/dev/null
    ./years.sh
    mvn clean install -Pqulice-profile -Pqulice --errors --settings ../settings.xml
    mvn clean site -Psite --errors --settings ../settings.xml
    mvn clean
  commanders:
  - caarlos0
  - carlosmiranda
  - darkled
  - dmzaytsev
  - ggajos
  - hdouss
  - krzyk
  - longtimeago
  - mkordas
  - original-brownbear
  - pinaf
deploy:
  script: |-
    mvn clean deploy -Pqulice-profile -Pqulice --errors --settings ../settings.xml
    mvn clean
    pdd --source=$(pwd) --verbose --file=qulice.xml --exclude=qulice-maven-plugin/src/it/**/*.java,qulice-checkstyle/src/test/resources/com/qulice/checkstyle/AtClauseOrder.java
    s3cmd --no-progress put qulice.xml --config=../s3cfg s3://pdd.teamed.io/qulice.xml
    est --dir=./est --verbose --file=qulice.xml --format=xml
    s3cmd --no-progress put qulice.xml --config=../s3cfg s3://est.teamed.io/qulice.xml
env:
  MAVEN_OPTS: -XX:MaxPermSize=256m -Xmx1g
release:
  script: |-
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Pqulice-profile -Pqulice -Psonatype --errors --settings ../settings.xml
    mvn clean site-deploy -Pgh-pages -Pqulice-profile -Psite --errors --settings ../settings.xml || echo 'site-deploy failed'
  commanders:
  - krzyk
  - yegor256